create table if not exists usuario_groups (
    id bigint generated by default as identity primary key,
    customuser_id uuid not null,
    group_id integer not null,
    unique (customuser_id, group_id),
    foreign key (customuser_id)
        references usuario (id_usuario)
        on delete cascade,
    foreign key (group_id)
        references auth_group (id)
        on delete cascade
);

create table if not exists usuario_user_permissions (
    id bigint generated by default as identity primary key,
    customuser_id uuid not null,
    permission_id integer not null,
    unique (customuser_id, permission_id),
    foreign key (customuser_id)
        references usuario (id_usuario)
        on delete cascade,
    foreign key (permission_id)
        references auth_permission (id)
        on delete cascade
);
